# Define o nome da ação
name: Run E2E Tests

# Define quando a ação será executada, nesse caso, toda vez que um pull request for feito
on: [pull_request]

# Define os trabalhos que serão executados
jobs:
  run-e2e-tests:
    # Define o nome do trabalho
    name: Run E2E Tests
    # Define o ambiente onde a ação será executada
    runs-on: ubuntu-latest

    services:
      # Define o serviço que será utilizado
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: findafriend

    steps:
      # Passo 1: Baixa o código dentro da nossa máquina
      - uses: actions/checkout@v3

      # Passo 2: Configura o ambiente do Node.js
      - uses: actions/setup-node@v3
        with:
          # Define a versão do Node.js
          node-version: 20
          cache: "npm"

      # Passo 3: Instala as dependências do projeto (ci: Instala as dependências de forma mais rápida)
      - run: npm ci

      # Passo 4: Executa os testes e2e
      - run: npm run test:e2e
        # Define as variáveis de ambiente
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/findafriend?schema=public"
          PORT: 3000
